name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps --unsafe-perm
      - run: npm install --ignore-scripts=false --foreground-scripts --verbose sharp
      - name: 🧪 Test
        run: npm test
      - name: 🚧 Build
        run: npm run build
      - uses: tobua/release-npm-action@v1
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
